spring.application.name=Pedidos360

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always


spring.datasource.url=jdbc:mysql://localhost:3306/pedidos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=microservicio
spring.datasource.password=system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cambiado a 'update' para no borrar los pedidos al apagar la aplicación
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

server.port=8080

# Requiere dependencia springdoc-openapi-starter-webmvc-ui en el pom.xml
springdoc.swagger-ui.path=/swagger.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operations-sorter=alpha