spring.application.name=Pedidos360

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always


spring.datasource.url=jdbc:mysql://pedidos-360.cye5cunhy7aj.us-east-1.rds.amazonaws.com:3306/pedidos360
spring.datasource.username=admin
spring.datasource.password=ContrasenaMaestra
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# Puerto libre para desarrollo local; 8080 y 8081 ya están ocupados
server.port=8085

# Habilitar integración con Azure AD
spring.cloud.azure.active-directory.enabled=true

# Tenant ID de Microsoft Entra ID
spring.cloud.azure.active-directory.profile.tenant-id=ac6019c7-78df-4d97-9d85-291001476eb0

# Client ID del registro del API en Entra ID (Pedidos360-Backend-Angular)
spring.cloud.azure.active-directory.credential.client-id=f900a1e2-036a-485f-b14f-c22a1ccf7005

# Application ID URI configurado en "Expose an API"
spring.cloud.azure.active-directory.app-id-uri=api://f900a1e2-036a-485f-b14f-c22a1ccf7005

